=== cchdo/params/src/cchdo/params/parameters.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "whp_name": {
        "type": "string",
        "minLength": 2
      },
      "whp_unit": {
        "type": ["string", "null"],
        "minLength": 1
      },
      "whp_number": {
        "type": ["number"],
        "description": "The WHP Parameter Number assigned by the WHPO, there is no requirement that all params have a number or for numbers to be unique to a single parameter."
      },
      "error_name":{
        "type": ["string"]
      },
      "flag_w": {
        "enum": ["woce_bottle", "woce_ctd", "woce_discrete", null]
      },
      "cf_name": {
        "type": ["string", "null"],
        "minLength": 3
      },
      "cf_unit": {
        "type": ["string", "null"],
        "minLength": 1,
        "description": "Units to use if the actual unit in a CF-netcdf is different from the cf canonical unit, examples: degC instead of K for sea water temp or even umol/kg insead of mol/kg"
      },
      "reference_scale": {
        "type": ["string", "null"],
        "minLength": 1,
        "description": "For some parameters, the calibration scale used e.g. ITS-90, IPTS-68, or unknown"
      },
      "data_type": {
        "enum": ["decimal", "integer", "string"]
      },
      "numeric_min": {
        "type": ["number"]
      },
      "numeric_max": {
        "type": ["number"]
      },
      "numeric_precision": {
        "type": "integer",
        "minimum": 0
      },
      "field_width": {
        "type": "integer",
        "minimum": 1
      },
      "description": {
        "type": ["string", "null"]
      },
      "note": {
        "type": ["string", "null"]
      },
      "warning": {
        "type": ["string", "null"]
      },
      "scope": {
        "enum": ["cruise", "profile", "sample"]
      }
    },
    "required": [
      "whp_name",
      "whp_unit",
      "flag_w",
      "data_type",
      "field_width"
    ],
    "additionalProperties": false,
        "dependencies": {
          "numeric_min": {
            "properties": {
              "data_type": {
                "type": "string",
                "enum": ["decimal", "integer"]
              }
            }
          },
          "numeric_max": {
            "properties": {
              "data_type": {
                "type": "string",
                "enum": ["decimal", "integer"]
              }
            }
          },
          "numeric_precision": {
            "properties": {
              "data_type": {
                "type": "string",
                "enum": ["decimal", "integer"]
              }
            }
          }
        }
  }
}

=== cchdo/params/legacy/parameters.json
[
  {
    "data_type": "string", 
    "description": "The expedition code, assigned by the CCHDO or generated by the user. Used as the unique identifier for the cruise. Usual generation formula is ICES 4 character platform code then the cruise departure date in YYYYMMDD format. The underscore ``_`` character may also be present.", 
    "field_width": 14, 
    "flag_w": null, 
    "whp_name": "EXPOCODE", 
    "whp_unit": null,
    "scope": "profile"
  }, 
  {
    "data_type": "string", 
    "description": "If a repeat of a WOCE section, this is the WHP section identifier. Examples include: ``A12``, ``A13.5``, ``P02``.", 
    "field_width": 11, 
    "flag_w": null, 
    "note": "There may be inconsistency in the how line numbers are represented. For example, ``P02`` might be present as ``P2``, these represent the same SECT_ID. Two digit zero padded line numbers are the canonical representation, please inform the CCHDO if non zero padded line numbers are encountered.", 
    "whp_name": "SECT_ID", 
    "whp_unit": null,
    "scope": "profile"
  }, 
  {
    "data_type": "string", 
    "description": "The originator's station identifier. Allowed characters are U+0030 to U+0039, U+0041 to U+005A, U+0061 to U+007A, and U+005F (``0-9``, ``a-z``, ``A-Z``, and ``_``)", 
    "field_width": 8, 
    "flag_w": null, 
    "note": "Numeric-only station identifiers are preferred by many data users, but provision for non numeric station identifiers is retained to maintain compatibility with WOCE records.", 
    "whp_name": "STNNBR", 
    "whp_unit": null,
    "scope": "profile"
  }, 
  {
    "data_type": "integer", 
    "description": "The originator's cast number.", 
    "field_width": 3, 
    "flag_w": null, 
    "note": "Where cast number is unknown a default value of 1 MAY be inserted by data processors.", 
    "whp_name": "CASTNO", 
    "whp_unit": null,
    "scope": "profile"
  }, 
    {
    "data_type": "integer", 
    "description": "BIOS cast number. Used by the Bermuda Institute of Ocean Sciences in the BATS and Hydrostation S timeseries.", 
    "field_width": 8, 
    "flag_w": null, 
    "whp_name": "BIOS_CASTID", 
    "whp_unit": null,
    "scope": "profile"
  }, 
  {
    "data_type": "string", 
    "description": "The sample number. Often it is the rosette position, however, groups may use their own sampling identification scheme. Allowed characters are U+0030 to U+0039, U+0041 to U+005A, U+0061 to U+007A, and U+005F (``0-9``, ``a-z``, ``A-Z``, and ``_``)", 
    "field_width": 11, 
    "flag_w": null, 
    "warning": "The value may not be numeric, ensure that any software reading the file can handle UTF-8 data of the specified allowed code points.", 
    "whp_name": "SAMPNO", 
    "whp_unit": null,
    "scope": "sample"
  }, 
  {
    "data_type": "integer", 
    "description": "The GEOTRACES Event number. Along with the GEOTRACES sample number, it is used by the GEOTRACES community for sample identification.", 
    "field_width": 8, 
    "flag_w": null, 
    "whp_name": "GEOTR_EVENT", 
    "whp_unit": null,
    "scope": "profile"
  }, 
  {
    "data_type": "integer", 
    "description": "The GEOTRACES Sample number. Along with the GEOTRACES Event number, it is used by the GEOTRACES community for sample identification.", 
    "field_width": 8, 
    "flag_w": null, 
    "whp_name": "GEOTR_SAMPNO", 
    "whp_unit": null,
    "scope": "sample"
  }, 
  {
    "data_type": "string", 
    "description": "Sample identification number used by the Bedford Institute of Oceanography (BIO)", 
    "field_width": 11, 
    "flag_w": null, 
    "whp_name": "BIONBR", 
    "whp_unit": null
  }, 
  {
    "data_type": "string", 
    "description": "The bottle identification number. This is intended to be a permanent, unique serial number fixed to the sampling device. It may also be the an identifier fixed for the duration of a single expedition. Allowed characters are U+0030 to U+0039, U+0041 to U+005A, U+0061 to U+007A, and U+005F (``0-9``, ``a-z``, ``A-Z``, and ``_``)", 
    "field_width": 11, 
    "flag_w": "woce_bottle", 
    "note": "The bottle number MAY have quality flags.", 
    "warning": "The value may not be numeric, ensure that any software reading the file can handle UTF-8 data of the specified allowed code points.", 
    "whp_name": "BTLNBR", 
    "whp_unit": null
  }, 
  {
    "data_type": "string", 
    "description": "The UTC date in zero padded YYYYMMDD format. The date reported is usually cast bottom for Bottle files and cast start for CTD files. Valid range for YYYY: 0001-9999. Valid range for MM: 01-12. Valid range for DD: 01-31 (depends on month and year). The format of dates corresponds to the C-strftime format of ``%Y%m%d``.\n\nThe date should be read as a string, but be able to be cast unambiguously to an integer. To convert from integer representation, left pad zeros to match the date format description. For example, the integer ``8020202`` is the date ``08020202`` or Feb 2nd, 802. This is a very unlikely situation.", 
    "field_width": 8, 
    "flag_w": null, 
    "whp_name": "DATE", 
    "whp_unit": null,
    "scope": "profile"
  }, 
  {
    "data_type": "string", 
    "description": "The UTC time in zero padded hhmm format. A single time should be reported for each cast, usually the time at cast bottom (deepest) is used. The order of preference for the reported time is: cast bottom, cast start, cast end (i.e if cast bottom is not available, the cast start time should be used).\n\nValid range for hh: 00-24 Valid range for mm: 00-59 The format of times corresponds to the C-strftime format of ``%H%M``.\n\nThe time should be read as a string, but be able to be cast unambiguously into an integer. To convert from an integer, left pad zeros to match the time format description.", 
    "field_width": 11, 
    "flag_w": null, 
    "note": "Times represented as integers will be present in whp COARDS netcdf files. Times in netcdf files will be anywhere from 1 to 4 digits. E.g. a time of 6 as in integer represents 6 minutes after midnight or 0006\n\nMidnight is a special case in that it has two valid representations: ``0000`` and ``2400``. The date ``20140202`` at time ``0000`` is the same instant as the date ``20140201`` at time ``2400``. This corresponds to times allowed by ISO 8601.\n\nUse `BTL_TIME`_ to report the time of individual bottle closures.\n\nCF netCDF files will use the standard Time Coordinate as specified in the conventions", 
    "warning": "Time is not a required parameter! If time is not present, then the temporal resolution of the data is reduced to a 24 hour period. It is the responsibility of the user of the data to omit files/casts which do not meet their temporal resolution requirements.", 
    "whp_name": "TIME", 
    "whp_unit": null,
    "scope": "profile"
  }, 
  {
    "data_type": "decimal", 
    "description": "The latitude as a signed decimal number. By convention, is positive in the northern hemisphere and negative in the southern hemisphere. Positive values do not include a ``+`` character (U+002B), negative values are prefixed with a ``-`` character (U+002D).", 
    "field_width": 9, 
    "flag_w": null, 
    "note": "Only one latitude SHOULD be reported for a cast, typically this is the ship position when the cast is at the bottom (deepest), but this is not guaranteed.\n\nUse `BTL_LAT`_ to include positions of individual bottle closures.", 
    "numeric_max": 90, 
    "numeric_min": -90, 
    "numeric_precision": 4, 
    "warning": "Since this parameter has no units, the positive in the northern hemisphere and negative in the southern hemisphere MUST be strictly adhered to.\n\nThe geographic coordinate system is not currently reported.", 
    "whp_name": "LATITUDE", 
    "whp_unit": null,
    "cf_name": "latitude",
    "scope": "profile"
  }, 
  {
    "data_type": "decimal", 
    "description": "The longitude as a signed decimal number. By convention, is positive in the eastern hemisphere and negative in the western hemisphere. Positive values do not include a ``+`` character (U+002B), negative values are prefixed with a ``-`` character (U+002D).", 
    "field_width": 11, 
    "flag_w": null, 
    "note": "Only one longitude SHOULD be reported for a cast, typically this is the ship position when the cast is at the bottom (deepest), but this is not guaranteed.\n\nUse `BTL_LON`_ to include positions of individual bottle closures.\n\nThe longitudes of -180 and 180 describe the same meridian.", 
    "numeric_max": 180, 
    "numeric_min": -180, 
    "warning": "Since this parameter has no units, the positive in the eastern hemisphere and negative in the western hemisphere convention MUST be strictly adhered to.\n\nThe geographic coordinate system is not currently reported.", 
    "whp_name": "LONGITUDE", 
    "whp_unit": null,
    "cf_name": "longitude",
    "scope": "profile"
  }, 
  {
    "data_type": "decimal", 
    "description": "The reported depth to the bottom. Corrected depths are preferred to uncorrected depths.", 
    "field_width": 9, 
    "flag_w": null, 
    "note": "Documentation should be provided describing how the depth was calculated/corrected, typically in the comment fields.", 
    "numeric_precision": 1, 
    "warning": "This is NOT the depth of bottle closures.", 
    "whp_name": "DEPTH", 
    "whp_unit": "METERS",
    "cf_name": "sea_floor_depth_below_sea_surface",
    "scope": "profile"
  }, 
  {
    "data_type": "decimal", 
    "description": "The corrected pressure as measured by the CTD.", 
    "field_width": 8, 
    "flag_w": "woce_ctd", 
    "note": "Typically does not have quality flags.", 
    "numeric_max": 10000.0, 
    "numeric_min": 0.0, 
    "numeric_precision": 1, 
    "whp_name": "CTDPRS", 
    "whp_unit": "DBAR",
    "cf_name": "sea_water_pressure"
  }, 
  {
    "data_type": "decimal",
