=== cchdo/params/legacy/aliases.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "whp_name": {
          "type": "string",
          "minLength": 2
        },
        "whp_unit": {
          "type": ["string", "null"],
          "minLength": 1
        },
        "canonical_name": {
          "type": "string",
          "minLength": 2
        },
        "canonical_unit": {
          "type": ["string", "null"],
          "minLength": 1
        }
      },
      "required": [
        "whp_name",
        "whp_unit",
        "canonical_name",
        "canonical_unit"
      ]
    }
  }

=== cchdo/params/legacy/aliases.json
[
    {
        "whp_name": "LATITUDE",
        "whp_unit": "DEG",
        "canonical_name": "LATITUDE",
        "canonical_unit": null
    },
    {
        "whp_name": "LONGITUDE",
        "whp_unit": "DEG",
        "canonical_name": "LONGITUDE",
        "canonical_unit": null
    },
    {
        "whp_name": "DEPTH",
        "whp_unit": null,
        "canonical_name": "DEPTH",
        "canonical_unit": "METERS"
    },
    {
        "whp_name": "CTDPRS",
        "whp_unit": "DBARS",
        "canonical_name": "CTDPRS",
        "canonical_unit": "DBAR"
    },
    {
        "whp_name": "CTDPRS",
        "whp_unit": "DBR",
        "canonical_name": "CTDPRS",
        "canonical_unit": "DBAR"
    },
    {
        "whp_name": "CTDTMP",
        "whp_unit": "ITS90",
        "canonical_name": "CTDTMP",
        "canonical_unit": "ITS-90"
    },
    {
        "whp_name": "CTDTMP",
        "whp_unit": "IPTS-90",
        "canonical_name": "CTDTMP",
        "canonical_unit": "ITS-90"
    },
    {
        "whp_name": "CTDTMP",
        "whp_unit": "IT-90",
        "canonical_name": "CTDTMP",
        "canonical_unit": "ITS-90"
    },
    {
        "whp_name": "CTDTMP",
        "whp_unit": "ITS_90",
        "canonical_name": "CTDTMP",
        "canonical_unit": "ITS-90"
    },
    {
        "whp_name": "CTDTMP",
        "whp_unit": "ITS-68",
        "canonical_name": "CTDTMP",
        "canonical_unit": "IPTS-68"
    },
    {
        "whp_name": "CTDTMP",
        "whp_unit": "ITS_68",
        "canonical_name": "CTDTMP",
        "canonical_unit": "IPTS-68"
    },
    {
        "whp_name": "CTDTMP",
        "whp_unit": "IPTS68",
        "canonical_name": "CTDTMP",
        "canonical_unit": "IPTS-68"
    },
    {
        "whp_name": "CTDTMP",
        "whp_unit": "DEG-C",
        "canonical_name": "CTDTMP",
        "canonical_unit": "DEG C"
    },
    {
        "whp_name": "PH_TEMP",
        "whp_unit": "DEGC",
        "canonical_name": "PH_TMP",
        "canonical_unit": "DEG C"
    },
    {
        "whp_name": "TIME",
        "whp_unit": "UTC",
        "canonical_name": "TIME",
        "canonical_unit": null
    },
    {
        "whp_name": "THETA",
        "whp_unit": "DEGC",
        "canonical_name": "THETA",
        "canonical_unit": "DEG C"
    },
    {
        "whp_name": "THETA",
        "whp_unit": "DEC C",
        "canonical_name": "THETA",
        "canonical_unit": "DEG C"
    },
    {
        "whp_name": "THETA",
        "whp_unit": "DEC-C",
        "canonical_name": "THETA",
        "canonical_unit": "DEG C"
    },
    {
        "whp_name": "THETA",
        "whp_unit": "DEC_C",
        "canonical_name": "THETA",
        "canonical_unit": "DEG C"
    },
    {
        "whp_name": "AMMONI",
        "whp_unit": "UMOL/KG",
        "canonical_name": "NH4",
        "canonical_unit": "UMOL/KG"
    },
    {
        "whp_name": "DELC13",
        "whp_unit": "O/OO",
        "canonical_name": "DELC13",
        "canonical_unit": "/MILLE"
    },
    {
        "whp_name": "DELO18",
        "whp_unit": "O/OO",
        "canonical_name": "DELO18",
        "canonical_unit": "/MILLE"
    },
    {
        "whp_name": "DELC14",
        "whp_unit": "O/OO",
        "canonical_name": "DELC14",
        "canonical_unit": "/MILLE"
    },
    {
        "whp_name": "SALNTY",
        "whp_unit": "PSU",
        "canonical_name": "SALNTY",
        "canonical_unit": "PSS-78"
    },
    {
        "whp_name": "SALNTY",
        "whp_unit": "PSS78",
        "canonical_name": "SALNTY",
        "canonical_unit": "PSS-78"
    },
    {
        "whp_name": "CTDSAL",
        "whp_unit": "PSU",
        "canonical_name": "CTDSAL",
        "canonical_unit": "PSS-78"
    },
    {
        "whp_name": "CTDRAW",
        "whp_unit": null,
        "canonical_name": "CTDRAW",
        "canonical_unit": "DBAR"
    },
    {
        "whp_name": "REVTMP",
        "whp_unit": null,
        "canonical_name": "REVTMP",
        "canonical_unit": "DEG C"
    },
    {
        "whp_name": "REVTMP",
        "whp_unit": "ITS-68",
        "canonical_name": "REVTMP",
        "canonical_unit": "IPTS-68"
    },
    {
        "whp_name": "CTDTMP",
        "whp_unit": "ITST90",
        "canonical_name": "CTDTMP",
        "canonical_unit": "ITS-90"
    },
    {
        "whp_name": "CTDTMP",
        "whp_unit": "DEGC",
        "canonical_name": "CTDTMP",
        "canonical_unit": "DEG C"
    },
    {
        "whp_name": "CTDTMP",
        "whp_unit": "DEG_C",
        "canonical_name": "CTDTMP",
        "canonical_unit": "DEG C"
    },
    {
        "whp_name": "CTDSAL",
        "whp_unit": "PSS78",
        "canonical_name": "CTDSAL",
        "canonical_unit": "PSS-78"
    },
    {
        "whp_name": "SBE35",
        "whp_unit": "ITS-90",
        "canonical_name": "REFTMP",
        "canonical_unit": "ITS-90"
    },
    {
        "whp_name": "XMISS",
        "whp_unit": "%TRANS",
        "canonical_name": "CTDXMISS",
        "canonical_unit": "%TRANS"
    },
    {
        "whp_name": "XMISS",
        "whp_unit": "0-5VDC",
        "canonical_name": "CTDXMISS",
        "canonical_unit": "0-5VDC"
    },
    {
        "whp_name": "CFC-12",
        "whp_unit": "PM/KG",
        "canonical_name": "CFC-12",
        "canonical_unit": "PMOL/KG"
    },
    {
        "whp_name": "CFC-11",
        "whp_unit": "PM/KG",
        "canonical_name": "CFC-11",
        "canonical_unit": "PMOL/KG"
    },
    {
        "whp_name": "RA-226",
        "whp_unit": "DPM/100KG",
        "canonical_name": "RA-226",
        "canonical_unit": "DM/.1MG"
    },
    {
        "whp_name": "PCO2TMP",
        "whp_unit": "DEG_C",
        "canonical_name": "PCO2TMP",
        "canonical_unit": "DEG C"
    },
    {
        "whp_name": "NO3+NO2",
        "whp_unit": "UMOL/KG",
        "canonical_name": "NO2+NO3",
        "canonical_unit": "UMOL/KG"
    },
    {
        "whp_name": "CTDOXY",
        "whp_unit": "uMOL/KG",
        "canonical_name": "CTDOXY",
        "canonical_unit": "UMOL/KG"
    },
    {
        "whp_name": "CTDETIME",
        "whp_unit": null,
        "canonical_name": "CTDETIME",
        "canonical_unit": "SECONDS"
    },
    {
        "whp_name": "SECT",
        "whp_unit": null,
        "canonical_name": "SECT_ID",
        "canonical_unit": null
    },
    {
        "whp_name": "NUMBER",
        "whp_unit": "OBS.",
        "canonical_name": "CTDNOBS",
        "canonical_unit": null
    },
    {
        "whp_name": "CTDPAR",
        "whp_unit": "uE/m^2/sec",
        "canonical_name": "PAR",
        "canonical_unit": "UMOL/M^2/SEC"
    },
    {
        "whp_name": "CTDPAR",
        "whp_unit": "UEINSTEINS/M2.SEC",
        "canonical_name": "PAR",
        "canonical_unit": "UMOL/M^2/SEC"
    },
    {
        "whp_name": "CTDPAR",
        "whp_unit": "UMOL/M^2/S",
        "canonical_name": "PAR",
        "canonical_unit": "UMOL/M^2/SEC"
    },
    {
        "whp_name": "PAR",
        "whp_unit": "UEINSTEINS/M2.SEC",
        "canonical_name": "PAR",
        "canonical_unit": "UMOL/M^2/SEC"
    },
    {
        "whp_name": "PAR",
        "whp_unit": "uE/m^2/sec",
        "canonical_name": "PAR",
        "canonical_unit": "UMOL/M^2/SEC"
    },
    {
        "whp_name": "CTDNOBS",
        "whp_unit": "ARBITRARY",
        "canonical_name": "CTDNOBS",
        "canonical_unit": null
    }
]
